### testing api call

### User
### Get user
GET http://localhost:8000/


### Post new user
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
    "name":"subekshya", 
    "email":"xa@gmail.com", 
    "password":"123s"
}

### Login user
POST http://localhost:8000/api/v1/users/login
Content-Type: application/json

{ 
    "email":"xa@gmail.com", 
    "password":"123s"
}

###Transactions